### ISSUE TITLE
Failed compiling / installing 3.2.0

### ISSUE THREAD

**Issue by highstrike** [fivdi/pigpio#109]
Sup?

So I tried building a docker image for my raspberry pi 4 but I can't install the newest version which is 3.2.0. However it works just fine with 3.1.1.

This is my [Dockerfile](https://github.com/highstrike/raspberry-ready/blob/69a616eae8a64ccb6b3cdfc280ffc35cadf05720/Dockerfile) and I just built the image (based on alpine linux) ignoring the last 2 lines so that I can go in it with exec to check things out manually.

So I just have a `package.json` file and the `start.js` script in the `/app` directory, all of the dependencies are are installed correctly and you can see the versions here:
![image](https://user-images.githubusercontent.com/2379538/80868735-18b18100-8ca5-11ea-86ea-8082c7926abe.png)

After running `npm install` with `pigpio:3.2.0` as a dependency I get the following error

```
/app # cat /root/.npm/_logs/2020-05-02T15_29_41_318Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session 94f4536c497ac96a
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall raspberry-ready@1.0.3
7 info lifecycle raspberry-ready@1.0.3~preinstall: raspberry-ready@1.0.3
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 21ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 304 https://registry.npmjs.org/pigpio 275ms (from cache)
18 silly pacote range manifest for pigpio@^3.1.1 fetched in 296ms
19 http fetch GET 304 https://registry.npmjs.org/bindings 67ms (from cache)
20 silly pacote range manifest for bindings@^1.5.0 fetched in 73ms
21 http fetch GET 304 https://registry.npmjs.org/nan 129ms (from cache)
22 silly pacote range manifest for nan@^2.14.1 fetched in 138ms
23 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 82ms (from cache)
24 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 87ms
25 silly pacote range manifest for pigpio@^3.1.1 fetched in 4ms
26 silly resolveWithNewModule pigpio@3.2.0 checking installable status
27 silly pacote range manifest for bindings@^1.5.0 fetched in 6ms
28 silly resolveWithNewModule bindings@1.5.0 checking installable status
29 silly pacote range manifest for nan@^2.14.1 fetched in 8ms
30 silly resolveWithNewModule nan@2.14.1 checking installable status
31 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 2ms
32 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
33 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 506ms
34 timing stage:loadIdealTree Completed in 515ms
35 silly currentTree raspberry-ready@1.0.3
36 silly idealTree raspberry-ready@1.0.3
36 silly idealTree +-- bindings@1.5.0
36 silly idealTree +-- file-uri-to-path@1.0.0
36 silly idealTree +-- nan@2.14.1
36 silly idealTree `-- pigpio@3.2.0
37 silly install generateActionsToTake
38 timing stage:generateActionsToTake Completed in 20ms
39 silly diffTrees action count 4
40 silly diffTrees add file-uri-to-path@1.0.0
41 silly diffTrees add bindings@1.5.0
42 silly diffTrees add nan@2.14.1
43 silly diffTrees add pigpio@3.2.0
44 silly decomposeActions action count 32
45 silly decomposeActions fetch file-uri-to-path@1.0.0
46 silly decomposeActions extract file-uri-to-path@1.0.0
47 silly decomposeActions preinstall file-uri-to-path@1.0.0
48 silly decomposeActions build file-uri-to-path@1.0.0
49 silly decomposeActions install file-uri-to-path@1.0.0
50 silly decomposeActions postinstall file-uri-to-path@1.0.0
51 silly decomposeActions finalize file-uri-to-path@1.0.0
52 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
53 silly decomposeActions fetch bindings@1.5.0
54 silly decomposeActions extract bindings@1.5.0
55 silly decomposeActions preinstall bindings@1.5.0
56 silly decomposeActions build bindings@1.5.0
57 silly decomposeActions install bindings@1.5.0
58 silly decomposeActions postinstall bindings@1.5.0
59 silly decomposeActions finalize bindings@1.5.0
60 silly decomposeActions refresh-package-json bindings@1.5.0
61 silly decomposeActions fetch nan@2.14.1
62 silly decomposeActions extract nan@2.14.1
63 silly decomposeActions preinstall nan@2.14.1
64 silly decomposeActions build nan@2.14.1
65 silly decomposeActions install nan@2.14.1
66 silly decomposeActions postinstall nan@2.14.1
67 silly decomposeActions finalize nan@2.14.1
68 silly decomposeActions refresh-package-json nan@2.14.1
69 silly decomposeActions fetch pigpio@3.2.0
70 silly decomposeActions extract pigpio@3.2.0
71 silly decomposeActions preinstall pigpio@3.2.0
72 silly decomposeActions build pigpio@3.2.0
73 silly decomposeActions install pigpio@3.2.0
74 silly decomposeActions postinstall pigpio@3.2.0
75 silly decomposeActions finalize pigpio@3.2.0
76 silly decomposeActions refresh-package-json pigpio@3.2.0
77 silly install executeActions
78 silly doSerial global-install 32
79 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
80 verbose lock using /root/.npm/_locks/staging-bd3355550c5a469e.lock for /app/node_modules/.staging
81 silly doParallel extract 4
82 silly extract file-uri-to-path@1.0.0
83 silly extract bindings@1.5.0
84 silly extract nan@2.14.1
85 silly extract pigpio@3.2.0
86 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
87 silly tarball trying bindings@^1.5.0 by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
88 silly tarball trying nan@^2.14.1 by hash: sha512-isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==
89 silly tarball trying pigpio@^3.1.1 by hash: sha512-tX8+6Fl8y+awI7d7YyaDMImUWrYe8rnvXPBw8OhGEsVXM70qM/vwGe7dqob2JHZkGTlaj0pxBAPSXhcXnbmUlA==
90 silly extract bindings@^1.5.0 extracted to /app/node_modules/.staging/bindings-68fa5548 (136ms)
91 silly extract file-uri-to-path@1.0.0 extracted to /app/node_modules/.staging/file-uri-to-path-a0837616 (144ms)
92 silly extract nan@^2.14.1 extracted to /app/node_modules/.staging/nan-4b641147 (203ms)
93 silly extract pigpio@^3.1.1 extracted to /app/node_modules/.staging/pigpio-210f695b (244ms)
94 timing action:extract Completed in 251ms
95 silly doReverseSerial unbuild 32
96 silly doSerial remove 32
97 silly doSerial move 32
98 silly doSerial finalize 32
99 silly finalize /app/node_modules/file-uri-to-path
100 silly finalize /app/node_modules/bindings
101 silly finalize /app/node_modules/nan
102 silly finalize /app/node_modules/pigpio
103 timing action:finalize Completed in 18ms
104 silly doParallel refresh-package-json 4
105 silly refresh-package-json /app/node_modules/file-uri-to-path
106 silly refresh-package-json /app/node_modules/bindings
107 silly refresh-package-json /app/node_modules/nan
108 silly refresh-package-json /app/node_modules/pigpio
109 timing action:refresh-package-json Completed in 43ms
110 silly doParallel preinstall 4
111 silly preinstall file-uri-to-path@1.0.0
112 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
113 silly preinstall bindings@1.5.0
114 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
115 silly preinstall nan@2.14.1
116 info lifecycle nan@2.14.1~preinstall: nan@2.14.1
117 silly preinstall pigpio@3.2.0
118 info lifecycle pigpio@3.2.0~preinstall: pigpio@3.2.0
119 timing action:preinstall Completed in 2ms
120 silly doSerial build 32
121 silly build file-uri-to-path@1.0.0
122 info linkStuff file-uri-to-path@1.0.0
123 silly linkStuff file-uri-to-path@1.0.0 has /app/node_modules as its parent node_modules
124 silly build bindings@1.5.0
125 info linkStuff bindings@1.5.0
126 silly linkStuff bindings@1.5.0 has /app/node_modules as its parent node_modules
127 silly build nan@2.14.1
128 info linkStuff nan@2.14.1
129 silly linkStuff nan@2.14.1 has /app/node_modules as its parent node_modules
130 silly build pigpio@3.2.0
131 info linkStuff pigpio@3.2.0
132 silly linkStuff pigpio@3.2.0 has /app/node_modules as its parent node_modules
133 timing action:build Completed in 5ms
134 silly doSerial global-link 32
135 silly doParallel update-linked 0
136 silly doSerial install 32
137 silly install file-uri-to-path@1.0.0
138 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
139 silly install bindings@1.5.0
140 info lifecycle bindings@1.5.0~install: bindings@1.5.0
141 silly install nan@2.14.1
142 info lifecycle nan@2.14.1~install: nan@2.14.1
143 silly install pigpio@3.2.0
144 info lifecycle pigpio@3.2.0~install: pigpio@3.2.0
145 verbose lifecycle pigpio@3.2.0~install: unsafe-perm in lifecycle false
146 verbose lifecycle pigpio@3.2.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/pigpio/node_modules/.bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
147 verbose lifecycle pigpio@3.2.0~install: CWD: /app/node_modules/pigpio
148 silly lifecycle pigpio@3.2.0~install: Args: [ '-c', 'node-gyp rebuild' ]
149 timing audit submit Completed in 392ms
150 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 392ms
151 timing audit body Completed in 1ms
152 silly lifecycle pigpio@3.2.0~install: Returned: code: 1  signal: null
153 info lifecycle pigpio@3.2.0~install: Failed to exec install script
154 timing action:install Completed in 952ms
155 verbose unlock done using /root/.npm/_locks/staging-bd3355550c5a469e.lock for /app/node_modules/.staging
156 timing stage:rollbackFailedOptional Completed in 61ms
157 timing stage:runTopLevelLifecycles Completed in 1998ms
158 silly saveTree raspberry-ready@1.0.3
158 silly saveTree `-- pigpio@3.2.0
158 silly saveTree   +-- bindings@1.5.0
158 silly saveTree   | `-- file-uri-to-path@1.0.0
158 silly saveTree   `-- nan@2.14.1
159 verbose stack Error: pigpio@3.2.0 install: `node-gyp rebuild`
159 verbose stack Exit status 1
159 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
159 verbose stack     at EventEmitter.emit (events.js:310:20)
159 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
159 verbose stack     at ChildProcess.emit (events.js:310:20)
159 verbose stack     at maybeClose (internal/child_process.js:1021:16)
159 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
160 verbose pkgid pigpio@3.2.0
161 verbose cwd /app
162 verbose Linux 4.19.97-v7l+
163 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
164 verbose node v12.16.2
165 verbose npm  v6.14.4
166 error code ELIFECYCLE
167 error errno 1
168 error pigpio@3.2.0 install: `node-gyp rebuild`
168 error Exit status 1
169 error Failed at the pigpio@3.2.0 install script.
169 error This is probably not a problem with npm. There is likely additional logging output above.
170 verbose exit [ 1, true ]
```

But switching to `pigpio:3.1.1` and it works just fine:
![image](https://user-images.githubusercontent.com/2379538/80868927-1996e280-8ca6-11ea-9a7e-94f29fa70523.png)

I'm also running the latest raspbian buster with the following kernel
![image](https://user-images.githubusercontent.com/2379538/80869641-4d740700-8caa-11ea-9fee-444daed29e71.png)

And this is my docker version
![image](https://user-images.githubusercontent.com/2379538/80869692-8b712b00-8caa-11ea-9d24-ab640176650b.png)

**Comment by highstrike** [comment]
Forgot to add, running `npm install` with `3.2.0` directly on my raspberry pi, it works, it just doesn't work in docker while `3.1.1` works fine there.

**Comment by fivdi** [comment]
Sorry about that.

What's new in pigpio@3.2.0 is [this line in binding.gyp](https://github.com/fivdi/pigpio/blob/v3.2.0/binding.gyp#L7):
```
          '"<!(ldconfig -p | grep libpigpio.so | wc -l)" != "0"', {
```
It basically runs the command `ldconfig -p | grep libpigpio.so | wc -l` to see if the pigpic C library has been installed. The pigpio Node.js module depends on the pigpio C libarry.

Is it possible that the Docker image has problems running the command `ldconfig -p | grep libpigpio.so | wc -l`?

There appears to be something special about `ldconfig` in the Dockerfile. For example see [this line](https://github.com/highstrike/raspberry-ready/blob/v1.0.4/Dockerfile#L12):
```
    sed -i 's/ldconfig/ldconfig \/usr\/local/g' Makefile && \
```

**Comment by highstrike** [comment]
So the build instruction you mentioned changes the `Makefile` file by adding `/usr/local` to `ldconfig` as you can see below
![image](https://user-images.githubusercontent.com/2379538/80871520-c62c9080-8cb5-11ea-8af5-568da8024f48.png)

Otherwise the `make install` command fails.

Indeed docker (on alpine linux) has an issue with the `-p` argument
![image](https://user-images.githubusercontent.com/2379538/80871597-27ecfa80-8cb6-11ea-9af3-2b35329a2b62.png)

Hmm

**Comment by fivdi** [comment]
What the docker (on alpine Linux) output for the following command?
```
strings /etc/ld.so.cache | grep libpigpio.so
```

**Comment by highstrike** [comment]
![image](https://user-images.githubusercontent.com/2379538/80872961-fc6e0e00-8cbd-11ea-9a40-c7176614a387.png)

apparently alpine doesn't have such a file

**Comment by fivdi** [comment]
>apparently alpine doesn't have such a file

Indeed. It doesn't appear to have very much.

What does docker (on alpine Linux) output for the following command?
```
which pigpiod
```

**Comment by highstrike** [comment]
Yeah, alpine is a very light weight linux distro, very popular with docker.

It found the pigpiod in `/usr/local/bin/pigpiod`

![image](https://user-images.githubusercontent.com/2379538/80873582-5a9cf000-8cc2-11ea-9fdf-47a51af2dc94.png)

**Comment by fivdi** [comment]
Ok, that's good. It should be possible to fix the problem.

**Comment by highstrike** [comment]
Maybe this can also be of assistance

![image](https://user-images.githubusercontent.com/2379538/80890783-3c39f300-8cc8-11ea-9f22-dbe5d1773166.png)

**Comment by fivdi** [comment]
`find` would work but it will be very slow on a Raspberry Pi 0. Also, I don't want to use `sudo` and without `sudo` there will be a ton of error messages. `which pigpiod` is good.

81d205fb3a812c56b9423ce9c5369bd14522cae2 should fix the problem.

Please give it a try with pigpio@3.2.1 which has just been published on npm.

**Comment by highstrike** [comment]
Great success! You fixed it in `3.2.1`

Thank you! 🙇 

```
pi@raspberrypi:~/github/raspberry-ready $ docker build -t highstrike/raspberry-ready .
Sending build context to Docker daemon  120.3kB
Step 1/7 : FROM arm32v7/node:12.16.2-alpine
12.16.2-alpine: Pulling from arm32v7/node
3cfb62949d9d: Pull complete
f6fef232cef8: Pull complete
b4f416b96422: Pull complete
da5a829b9572: Pull complete
Digest: sha256:63377c2c43582a08c3db7235d051886cb313007b1050b8243f3455ba68e29012
Status: Downloaded newer image for arm32v7/node:12.16.2-alpine
 ---> 4ded18f99365
Step 2/7 : RUN apk --update --no-cache add --virtual dependencies curl build-base python &&     cd /tmp &&     curl -s https://api.github.com/repos/joan2937/pigpio/releases/latest     | grep 'tarball_url.*'     | cut -d : -f 2,3     | tr -d \",     | xargs -n 1 curl -sSL     | tar -xz --strip-components=1 &&     make &&     sed -i 's/ldconfig/ldconfig \/usr\/local/g' Makefile &&     make install
 ---> Running in e4b46737c6bb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
(1/30) Installing ca-certificates (20191127-r1)
(2/30) Installing nghttp2-libs (1.40.0-r0)
(3/30) Installing libcurl (7.67.0-r0)
(4/30) Installing curl (7.67.0-r0)
(5/30) Installing binutils (2.33.1-r0)
(6/30) Installing libmagic (5.37-r1)
(7/30) Installing file (5.37-r1)
(8/30) Installing gmp (6.1.2-r1)
(9/30) Installing isl (0.18-r0)
(10/30) Installing libgomp (9.2.0-r4)
(11/30) Installing libatomic (9.2.0-r4)
(12/30) Installing mpfr4 (4.0.2-r1)
(13/30) Installing mpc1 (1.1.0-r1)
(14/30) Installing gcc (9.2.0-r4)
(15/30) Installing musl-dev (1.1.24-r2)
(16/30) Installing libc-dev (0.7.2-r0)
(17/30) Installing g++ (9.2.0-r4)
(18/30) Installing make (4.2.1-r2)
(19/30) Installing fortify-headers (1.1-r0)
(20/30) Installing build-base (0.5-r1)
(21/30) Installing libbz2 (1.0.8-r1)
(22/30) Installing expat (2.2.9-r1)
(23/30) Installing libffi (3.2.1-r6)
(24/30) Installing gdbm (1.13-r1)
(25/30) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(26/30) Installing ncurses-libs (6.1_p20200118-r4)
(27/30) Installing readline (8.0.1-r0)
(28/30) Installing sqlite-libs (3.30.1-r1)
(29/30) Installing python2 (2.7.16-r3)
(30/30) Installing dependencies (20200502.200551)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 160 MiB in 46 packages
gcc -O3 -Wall -pthread -fpic -c -o pigpio.o pigpio.c
gcc -O3 -Wall -pthread -fpic -c -o command.o command.c
gcc -shared -pthread -Wl,-soname,libpigpio.so.1 -o libpigpio.so.1 pigpio.o command.o
ln -fs libpigpio.so.1 libpigpio.so
strip --strip-unneeded libpigpio.so
size     libpigpio.so
   text    data     bss     dec     hex filename
 222727    6116  605548  834391   cbb57 libpigpio.so
gcc -O3 -Wall -pthread -fpic -c -o pigpiod_if.o pigpiod_if.c
gcc -shared -pthread -Wl,-soname,libpigpiod_if.so.1 -o libpigpiod_if.so.1 pigpiod_if.o command.o
ln -fs libpigpiod_if.so.1 libpigpiod_if.so
strip --strip-unneeded libpigpiod_if.so
size     libpigpiod_if.so
   text    data     bss     dec     hex filename
  44147    5036   49272   98455   18097 libpigpiod_if.so
gcc -O3 -Wall -pthread -fpic -c -o pigpiod_if2.o pigpiod_if2.c
gcc -shared -pthread -Wl,-soname,libpigpiod_if2.so.1 -o libpigpiod_if2.so.1 pigpiod_if2.o command.o
ln -fs libpigpiod_if2.so.1 libpigpiod_if2.so
strip --strip-unneeded libpigpiod_if2.so
size     libpigpiod_if2.so
   text    data     bss     dec     hex filename
  55573    5040    2012   62625    f4a1 libpigpiod_if2.so
gcc -O3 -Wall -pthread   -c -o x_pigpio.o x_pigpio.c
gcc -o x_pigpio x_pigpio.o -L. -lpigpio -pthread -lrt
gcc -O3 -Wall -pthread   -c -o x_pigpiod_if.o x_pigpiod_if.c
gcc -o x_pigpiod_if x_pigpiod_if.o -L. -lpigpiod_if -pthread -lrt
gcc -O3 -Wall -pthread   -c -o x_pigpiod_if2.o x_pigpiod_if2.c
gcc -o x_pigpiod_if2 x_pigpiod_if2.o -L. -lpigpiod_if2 -pthread -lrt
gcc -O3 -Wall -pthread   -c -o pig2vcd.o pig2vcd.c
gcc -o pig2vcd pig2vcd.o
strip pig2vcd
gcc -O3 -Wall -pthread   -c -o pigpiod.o pigpiod.c
gcc -o pigpiod pigpiod.o -L. -lpigpio -pthread -lrt
strip pigpiod
gcc -O3 -Wall -pthread   -c -o pigs.o pigs.c
gcc -o pigs pigs.o command.o
strip pigs
install -m 0755 -d                             /opt/pigpio/cgi
install -m 0755 -d                             /usr/local/include
install -m 0644 pigpio.h                       /usr/local/include
install -m 0644 pigpiod_if.h                   /usr/local/include
install -m 0644 pigpiod_if2.h                  /usr/local/include
install -m 0755 -d                             /usr/local/lib
install -m 0755 libpigpio.so.1      /usr/local/lib
install -m 0755 libpigpiod_if.so.1  /usr/local/lib
install -m 0755 libpigpiod_if2.so.1 /usr/local/lib
cd /usr/local/lib && ln -fs libpigpio.so.1      libpigpio.so
cd /usr/local/lib && ln -fs libpigpiod_if.so.1  libpigpiod_if.so
cd /usr/local/lib && ln -fs libpigpiod_if2.so.1 libpigpiod_if2.so
install -m 0755 -d                             /usr/local/bin
install -m 0755 pig2vcd                        /usr/local/bin
install -m 0755 pigpiod                        /usr/local/bin
install -m 0755 pigs                           /usr/local/bin
if which python2; then python2 setup.py install ; fi
/usr/bin/python2
running install
running build
running build_py
creating build
creating build/lib
copying pigpio.py -> build/lib
running install_lib
copying build/lib/pigpio.py -> /usr/lib/python2.7/site-packages
byte-compiling /usr/lib/python2.7/site-packages/pigpio.py to pigpio.pyc
running install_egg_info
Writing /usr/lib/python2.7/site-packages/pigpio-1.46-py2.7.egg-info
if which python3; then python3 setup.py install ; fi
install -m 0755 -d                             /usr/local/man/man1
install -m 0644 p*.1                           /usr/local/man/man1
install -m 0755 -d                             /usr/local/man/man3
install -m 0644 p*.3                           /usr/local/man/man3
ldconfig /usr/local
Removing intermediate container e4b46737c6bb
 ---> 9fa79b1fa96c
Step 3/7 : WORKDIR /app
 ---> Running in a86aea59a4fb
Removing intermediate container a86aea59a4fb
 ---> a7203e85f2cb
Step 4/7 : COPY package.json /app
 ---> 14dfd0024c8a
Step 5/7 : RUN npm install --production &&     apk del dependencies &&     rm -rf /tmp/*
 ---> Running in 0c88218a570b

> pigpio@3.2.1 install /app/node_modules/pigpio
> node-gyp rebuild

make: Entering directory '/app/node_modules/pigpio/build'
  CXX(target) Release/obj.target/pigpio/src/pigpio.o
  SOLINK_MODULE(target) Release/obj.target/pigpio.node
  COPY Release/pigpio.node
make: Leaving directory '/app/node_modules/pigpio/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.

added 4 packages from 9 contributors and audited 501 packages in 17.927s
found 0 vulnerabilities

WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
(1/30) Purging dependencies (20200502.200551)
(2/30) Purging curl (7.67.0-r0)
(3/30) Purging build-base (0.5-r1)
(4/30) Purging file (5.37-r1)
(5/30) Purging g++ (9.2.0-r4)
(6/30) Purging gcc (9.2.0-r4)
(7/30) Purging binutils (2.33.1-r0)
(8/30) Purging libatomic (9.2.0-r4)
(9/30) Purging libgomp (9.2.0-r4)
(10/30) Purging make (4.2.1-r2)
(11/30) Purging libc-dev (0.7.2-r0)
(12/30) Purging musl-dev (1.1.24-r2)
(13/30) Purging fortify-headers (1.1-r0)
(14/30) Purging libcurl (7.67.0-r0)
(15/30) Purging ca-certificates (20191127-r1)
Executing ca-certificates-20191127-r1.post-deinstall
(16/30) Purging nghttp2-libs (1.40.0-r0)
(17/30) Purging libmagic (5.37-r1)
(18/30) Purging isl (0.18-r0)
(19/30) Purging mpc1 (1.1.0-r1)
(20/30) Purging mpfr4 (4.0.2-r1)
(21/30) Purging gmp (6.1.2-r1)
(22/30) Purging python2 (2.7.16-r3)
(23/30) Purging libbz2 (1.0.8-r1)
(24/30) Purging expat (2.2.9-r1)
(25/30) Purging libffi (3.2.1-r6)
(26/30) Purging gdbm (1.13-r1)
(27/30) Purging readline (8.0.1-r0)
(28/30) Purging ncurses-libs (6.1_p20200118-r4)
(29/30) Purging ncurses-terminfo-base (6.1_p20200118-r4)
(30/30) Purging sqlite-libs (3.30.1-r1)
Executing busybox-1.31.1-r9.trigger
OK: 5 MiB in 16 packages
Removing intermediate container 0c88218a570b
 ---> ab3717c5309f
Step 6/7 : COPY start.js /app
 ---> 7a3e8827ed90
Step 7/7 : CMD ["npm", "start"]
 ---> Running in 0c6675095ec2
Removing intermediate container 0c6675095ec2
 ---> 7401d98f25b4
Successfully built 7401d98f25b4
Successfully tagged highstrike/raspberry-ready:latest
```

**Comment by fivdi** [comment]
Excellent, thanks for the feedback.

**Comment by poegun** [comment]
pigpiod.service: Failed at step EXEC spawning /usr/local/bin/pigpiod: No such file or directory

I've been dealing with this problem for 10 days, no matter what I tried, I bought rpi5 for hobby purposes, what nonsense!
It's funny how something I bought for fun can stress me out and keep me awake!

@raspberrypi:~ $ sudo systemctl status pigpiod
× pigpiod.service - Daemon required to control GPIO pins via pigpio
     Loaded: loaded (/lib/systemd/system/pigpiod.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-09-10 14:03:44 BST; 1min 56s ago
   Duration: 751us
    Process: 10949 ExecStart=/usr/local/bin/pigpiod (code=exited, status=0/SUCCESS)
   Main PID: 10950 (code=exited, status=1/FAILURE)
        CPU: 2ms

Sep 10 14:03:44 raspberrypi pigpiod[10950]: 2024-09-10 14:03:44 gpioHardwareRevision: unknown rev code (d04170)
Sep 10 14:03:44 raspberrypi pigpiod[10950]: 2024-09-10 14:03:44 initCheckPermitted:
Sep 10 14:03:44 raspberrypi pigpiod[10950]: +---------------------------------------------------------+
Sep 10 14:03:44 raspberrypi pigpiod[10950]: |Sorry, this system does not appear to be a raspberry pi. |
Sep 10 14:03:44 raspberrypi pigpiod[10950]: |aborting.                                                |
Sep 10 14:03:44 raspberrypi pigpiod[10950]: +---------------------------------------------------------+
Sep 10 14:03:44 raspberrypi pigpiod[10950]: Can't initialise pigpio library
Sep 10 14:03:44 raspberrypi systemd[1]: Started pigpiod.service - Daemon required to control GPIO pins via pigpio.
Sep 10 14:03:44 raspberrypi systemd[1]: pigpiod.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 14:03:44 raspberrypi systemd[1]: pigpiod.service: Failed with result 'exit-code'.
